**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}
import pandas as pd
#Q1
df = pd.DataFrame(data)
#Q2
sub = df[(df.job == "teacher") | (df.job == "psychologist")] #for "or" you only require one stick
print(sub[sub["num_cars"] > sub["family_size"]])
#Q3
fam = df[(df["family_size"] <= 2) & (df["num_cars"] >= 1)] # this might not work without the brackets test that
print(fam)
#Q4
un = df.job.unique() #since unique is a function it needs to have brackets [see if you can use dot for this]
print(len(un))

   name           job  family_size  num_cars
5  Lisa  psychologist            3         4
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1
4


In [ ]:
# Q1-1
import pandas as pd
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}
df = pd.DataFrame(data)
print("Q1-1  ")
print(df)

# Q1-2
# Selecting people that are psychologist or teacher and their number of cars is greater than their family size.
print("\nQ1-2  ")
df_sub1 = df[(df['job'] == "psychologist") | (df['job'] == "teacher")]
df1 = df_sub1
df1['Check'] = (df_sub1['num_cars'] > df_sub1['family_size'])
print("People that are psychologist or teacher and their number of cars is greater than their family size:")
print(df1[df1['Check'].values] [['name', 'job','family_size', 'num_cars']])


# Q1-3
# Selecting people who have at most 2 family members and at least 1 car.
print("\nQ1-3  ")
df_sub = df[(df['family_size'] <= 2) & (df['num_cars'] >= 1)]
print("People who have at most 2 family members and at least 1 car:")
print(df_sub)

# Q1-4 
# Write a code that get number of unique jobs in this dataset.
arr = df["job"].unique()
print("\nQ1-4  ")
length = len(arr)
print("number of unqiue jobs in this dataset:", length)

print("\n")

Q1-1  
     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

Q1-2  
People that are psychologist or teacher and their number of cars is greater than their family size:
   name           job  family_size  num_cars
5  Lisa  psychologist            3         4

Q1-3  
People who have at most 2 family members and at least 1 car:
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

Q1-4  
number of unqiue jobs in this dataset: 4




/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))



In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
weights.groupby(fruit).mean()

banana    4.4
carrot    6.6
dtype: float64

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
import numpy as np

#Q3-1
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])
course_name_sort = np.sort(course_name)
for i in enumerate(course_name_sort):
  print(i)

#Q3-2
print("\nChecking whether each element of course name starts with P:")
print(course_name)
np.char.startswith(course_name, "P")


  

(0, 'JS')
(1, 'PHP')
(2, 'Python')
(3, 'examples')
(4, 'html')

Checking whether each element of course name starts with P:
['Python' 'JS' 'examples' 'PHP' 'html']


array([ True, False, False,  True, False])

**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
#Q4-1
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Q4-1")
print("Orignal array:", student_id)
reverse_student_id = np.flip(student_id) #reversing the array using flip
print("Reversed array:", reverse_student_id)

#Q4-2
print("\nQ4-2")
sorted_student_id = np.sort(student_id) #np.sort sorts arrays in ascending order?
print("The 3-largest values of student_id array:")
print(sorted_student_id[-3:])

Q4-1
Orignal array: [1023 5202 6230 1671 1682 5241 4532]
Reversed array: [4532 5241 1682 1671 6230 5202 1023]

Q4-2
The 3-largest values of student_id array:
[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
import numpy as np
a = np.array(0,100,1)
sum = 0
for i in a:
  if(a%3==0 | a%5 == 0):
    sum += a
print(sum)

In [ ]:

import numpy as np
a = np.arange(100)
index = np.where((a%3==0) | (a%5==0) ) #the where function gives the index positions
a = a[index] 
sum = a.sum() 
print("Sum of all the multiples of 3 or 5 below 100: ")
print(sum)

Sum of all the multiples of 3 or 5 below 100: 
2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

In [ ]:
import numpy as np
print("Orignal Array:")
arr = np.arange(12).reshape(3,4) 
print(arr)

# Q6.1
arr[:, [2, 1]] = arr[:, [1, 2]] #swap column 1 with column 2
print("\nQ6.1- Swapped Array (column 1 with column 2):")
print(arr)

# Q6.2
arr = np.arange(12).reshape(3,4)
arr[[0, 1], : ] = arr [[1, 0], :]
print("\nQ6.2- Swapped Array (row 1 with row 0):")
print(arr)

Orignal Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Q6.1- Swapped Array (column 1 with column 2):
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]

Q6.2- Swapped Array (row 1 with row 0):
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
